version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.2.3
jobs:
  test:
    docker:
      - image: cimg/elixir:1.12.2
    working_directory: ~/repo
    steps:
      - checkout
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix deps.get
      - run: mix format --check-formatted
      - run: mix test
      - run: mix credo --strict
      - run: mix docs
  demo:
    docker:
      - image: cimg/elixir:1.12.2-browsers
    working_directory: ~/repo
    steps:
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - checkout
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: cd demo && mix deps.get
      - run: cd demo && mix format --check-formatted
      - run: cd demo/assets && npm install
      - run: cd demo && mix test
workflows:
  version: 2
  build:
    jobs:
      - test
      - demo
